// 报告评估依据（大数据/循证医学证据库）
// 每个检测类别对应：科学依据、参考文献、循证风险因素、性别重点。
// 目标：让报告"有依据、可溯源"，提升专业度与加盟商信任度。
export interface EvidenceDef {
  code: string;
  scientificBasis: string;   // 该类别背后的真实科学原理
  reference: string;         // 文献/指南来源
  referenceUrl?: string;     // 可溯源链接
  riskFactors: string[];     // 循证风险因素（用于报告说明）
  genderNote?: string;       // 性别差异化说明
}

export const REPORT_EVIDENCE: Record<string, EvidenceDef> = {
  cardiovascular: {
    code: 'cardiovascular',
    scientificBasis: '心脑血管风险评估依据 Framingham 风险模型与《中国心血管病一级预防指南》：血压、血脂、血糖、BMI、吸烟、年龄与性别是主要独立危险因素，通过脉搏波/血流动力学参数可评估动脉弹性与血管年龄。',
    reference: '中国心血管病预防指南(2017)；Framingham Heart Study',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/9842025/',
    riskFactors: ['超重/肥胖(BMI≥24)', '高血压', '血脂异常', '糖尿病/糖耐量异常', '吸烟', '久坐', '年龄≥45(男)/≥55(女)'],
    genderNote: '男性 45 岁后、女性绝经后心血管风险显著上升，需重点观察冠脉供血、血管弹性与血压负荷。',
  },
  blood_lipid: {
    code: 'blood_lipid',
    scientificBasis: '血脂异常是动脉粥样硬化性心血管疾病(ASCVD)的核心危险因素。依据《中国血脂管理指南(2023)》，甘油三酯、低密度脂蛋白胆固醇(LDL-C)、高密度脂蛋白胆固醇(HDL-C)与总胆固醇需分层管理；肥胖与高甘油三酯血症强相关。',
    reference: '中国血脂管理指南(2023)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/36646805/',
    riskFactors: ['高脂饮食', '肥胖(尤其腹型)', '缺乏运动', '饮酒', '糖尿病', '甲状腺功能减退'],
  },
  blood_sugar: {
    code: 'blood_sugar',
    scientificBasis: '血糖代谢依据 WHO/《中国 2 型糖尿病防治指南》：空腹血糖、糖化血红蛋白(HbA1c)与胰岛素抵抗(IR)是评估糖代谢的核心；肥胖是 2 型糖尿病最重要的可逆危险因素。',
    reference: '中国 2 型糖尿病防治指南(2020版)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/31383613/',
    riskFactors: ['超重/肥胖', '高糖高精制碳水饮食', '糖尿病家族史', '缺乏运动', '年龄≥40', '妊娠期糖尿病史'],
  },
  obesity: {
    code: 'obesity',
    scientificBasis: '肥胖评估依据中国成人肥胖判定标准：BMI≥24 为超重、≥28 为肥胖，腰围男性≥90cm/女性≥85cm 为中心性肥胖。肥胖是代谢综合征的核心，显著增加心血管、糖尿病、睡眠呼吸暂停风险。',
    reference: '中国成人超重和肥胖预防控制指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/15273903/',
    riskFactors: ['高热量饮食', '久坐', '睡眠不足', '内分泌异常(甲减/库欣)', '药物', '遗传易感'],
  },
  body_composition: {
    code: 'body_composition',
    scientificBasis: '身体成分评估基于生物电阻抗分析(BIA)：通过弱电流测人体阻抗，估算体脂率、肌肉量、水分、基础代谢。BIA 与 DXA/水下称重一致性良好，正确操作下个体误差可控。',
    reference: 'BIA 身体成分测量原理与验证(PubMed 23299872)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/23299872/',
    riskFactors: ['体脂率过高(男>25%/女>30%)', '肌肉量不足(肌少症)', '内脏脂肪高', '水分失衡'],
  },
  thyroid: {
    code: 'thyroid',
    scientificBasis: '甲状腺功能评估依据《中国甲状腺疾病诊治指南》：TSH、FT3、FT4 及甲状腺相关抗体是核心指标；甲状腺功能异常(甲亢/甲减)影响代谢、心血管、神经精神与生殖。',
    reference: '中国甲状腺疾病诊治指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/28750100/',
    riskFactors: ['碘摄入异常', '自身免疫', '家族史', '女性(患病率更高)', '妊娠/产后', '精神压力'],
    genderNote: '女性甲状腺疾病患病率约为男性 5-8 倍，需重点观察 TSH、FT3/FT4 与甲状腺球蛋白。',
  },
  liver: {
    code: 'liver',
    scientificBasis: '肝功能评估依据《非酒精性脂肪性肝病防治指南》：转氨酶(ALT/AST)、胆红素、白蛋白反映肝细胞损伤与合成功能；肥胖与胰岛素抵抗是脂肪肝首要病因。',
    reference: '非酒精性脂肪性肝病防治指南(2018)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/29490623/',
    riskFactors: ['肥胖', '饮酒', '高脂高糖饮食', '病毒性肝炎', '药物性肝损伤', '熬夜'],
  },
  kidney: {
    code: 'kidney',
    scientificBasis: '肾功能评估依据 KDIGO 指南：估算肾小球滤过率(eGFR)、肌酐、尿素氮与尿蛋白是核心；高血压、糖尿病是慢性肾病主要病因。',
    reference: 'KDIGO 慢性肾脏病评估与管理指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/36074176/',
    riskFactors: ['高血压', '糖尿病', '高尿酸/痛风', '药物滥用', '肥胖', '慢性感染'],
  },
  gi_function: {
    code: 'gi_function',
    scientificBasis: '胃肠功能评估基于消化生理学：胃酸分泌、胃动力、肠道蠕动、消化酶活性与肠道菌群共同决定消化吸收；幽门螺杆菌与功能性胃肠病关系明确。',
    reference: '罗马IV功能性胃肠病标准；消化生理学共识',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/27144638/',
    riskFactors: ['幽门螺杆菌感染', '饮食不规律', '高脂辛辣', '压力焦虑', '滥用抑酸药/抗生素'],
  },
  gut_flora: {
    code: 'gut_flora',
    scientificBasis: '肠道菌群评估基于微生态学：菌群多样性与代谢、免疫、肠-脑轴密切相关；膳食纤维、益生菌与菌群结构互作。',
    reference: '人类肠道微生物组计划(HMP)；Nature 菌群与健康综述',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/31273223/',
    riskFactors: ['低膳食纤维饮食', '抗生素滥用', '高糖高脂', '久坐', '便秘/腹泻', '睡眠紊乱'],
  },
  bone_density: {
    code: 'bone_density',
    scientificBasis: '骨密度评估依据 WHO 骨质疏松诊断标准(骨密度 T 值)与《原发性骨质疏松症诊疗指南》：骨密度受年龄、性激素、钙/维D、运动影响。',
    reference: '原发性骨质疏松症诊疗指南(2022)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/36309613/',
    riskFactors: ['年龄增长(女性绝经后)', '钙/维生素D缺乏', '缺乏负重运动', '吸烟', '低体重', '糖皮质激素'],
    genderNote: '女性绝经后雌激素下降致骨量加速流失，骨质疏松风险显著高于男性。',
  },
  bone_disease: {
    code: 'bone_disease',
    scientificBasis: '骨病/关节评估基于骨关节流行病学：腰椎/颈椎退行性变、骨关节炎与年龄、劳损、肥胖、职业姿势相关。',
    reference: '骨关节炎诊疗指南；腰椎退行性疾病共识',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/30214462/',
    riskFactors: ['年龄≥50', '肥胖(负重关节)', '长期伏案/重体力', '既往损伤', '遗传'],
  },
  rheumatism: {
    code: 'rheumatism',
    scientificBasis: '风湿骨病评估依据风湿免疫学：类风湿因子、血沉(ESR)、C 反应蛋白(CRP)是炎症与免疫活动标志；寒冷潮湿与遗传是诱因。',
    reference: '类风湿关节炎诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/31196372/',
    riskFactors: ['遗传易感', '吸烟', '感染', '寒冷潮湿环境', '免疫异常'],
  },
  bone_growth: {
    code: 'bone_growth',
    scientificBasis: '骨生长发育评估基于骨龄学：儿童青少年骨龄、生长激素、钙磷代谢决定骨骼生长潜能。',
    reference: '儿童骨龄评估标准(GP/TW3 法)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/26621156/',
    riskFactors: ['生长激素缺乏', '钙/维D不足', '性早熟', '营养不良', '缺乏运动'],
  },
  gynecology: {
    code: 'gynecology',
    scientificBasis: '妇科评估依据妇科内分泌与炎症学：雌激素/孕激素、子宫附件、盆腔炎症标志物是核心；月经周期与内分泌轴(下丘脑-垂体-卵巢)密切相关。',
    reference: '中国妇科内分泌诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/30254783/',
    riskFactors: ['内分泌紊乱', '盆腔感染', '长期压力', '寒凉饮食', '作息紊乱', '多次人流'],
    genderNote: '女性专属：重点观察雌激素、孕激素、子宫、卵巢、盆腔与月经周期。',
  },
  breast: {
    code: 'breast',
    scientificBasis: '乳腺评估依据乳腺影像与内分泌学：乳腺增生与雌激素水平、月经周期相关；家族史与激素暴露是乳腺疾病主要风险。',
    reference: '中国乳腺癌筛查与乳腺增生诊疗共识',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/30522787/',
    riskFactors: ['雌激素长期暴露', '家族史', '晚育/未哺乳', '肥胖(绝经后)', '高脂饮食', '情绪压抑'],
    genderNote: '女性专属：乳腺增生、结节风险与雌激素水平及情绪压力强相关。',
  },
  menstrual: {
    code: 'menstrual',
    scientificBasis: '月经评估基于生殖内分泌轴：下丘脑-垂体-卵巢轴调节雌激素/孕激素周期性变化，决定月经规律、经量与痛经。',
    reference: '异常子宫出血与痛经诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/30109167/',
    riskFactors: ['内分泌紊乱', '多囊卵巢综合征(PCOS)', '贫血', '寒冷刺激', '精神压力', '体重异常'],
    genderNote: '女性专属：月经周期、经量、痛经与卵巢内分泌功能直接相关。',
  },
  allergy: {
    code: 'allergy',
    scientificBasis: '过敏原评估基于变态反应学：IgE 介导的 I 型超敏反应是过敏核心机制；食物、花粉、尘螨是常见过敏原。',
    reference: '过敏性鼻炎/哮喘诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/31787905/',
    riskFactors: ['家族过敏史', '免疫失衡', '环境过敏原暴露', '肠道菌群紊乱', '剖宫产/早期抗生素'],
    genderNote: '女性激素波动可影响免疫应答，过敏性疾病表现常与月经周期相关。',
  },
  endocrine: {
    code: 'endocrine',
    scientificBasis: '内分泌评估基于内分泌轴调控：甲状腺、肾上腺、性腺、胰岛等腺体通过激素网络调节代谢、生殖、应激与生长。',
    reference: '内分泌学原理(Williams Textbook of Endocrinology)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/27344602/',
    riskFactors: ['慢性压力(皮质醇升高)', '睡眠紊乱', '肥胖', '甲状腺/性腺异常', '环境内分泌干扰物'],
    genderNote: '女性内分泌受月经周期、妊娠、更年期显著影响，需动态观察雌激素/孕激素/甲状腺激素。',
  },
  hormone: {
    code: 'hormone',
    scientificBasis: '荷尔蒙评估基于内分泌生殖轴：雌激素、孕激素、睾酮、皮质醇、褪黑素等激素平衡影响情绪、睡眠、代谢与生殖健康。',
    reference: '性激素与健康(内分泌学会指南)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/29559975/',
    riskFactors: ['压力大', '熬夜(褪黑素下降)', '肥胖(芳香化酶致雌激素异常)', '更年期', '内分泌干扰物'],
    genderNote: '女性雌激素主导，男性睾酮主导；失衡分别表现为月经/更年期症状与精力/肌肉/性功能下降。',
  },
  prostate: {
    code: 'prostate',
    scientificBasis: '前列腺评估依据泌尿外科指南：前列腺体积、PSA、尿流率与残余尿是核心；年龄与雄激素是主要影响因素。',
    reference: '中国良性前列腺增生诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/30077317/',
    riskFactors: ['年龄≥45', '久坐', '饮酒', '辛辣饮食', '憋尿', '前列腺炎史'],
    genderNote: '男性专属：45 岁后前列腺增生风险逐年上升，PSA 与尿流率需重点观察。',
  },
  male_sexual: {
    code: 'male_sexual',
    scientificBasis: '男性功能评估基于男科学：睾酮水平、血管内皮功能、神经调控与心理状态共同决定；血管性因素与代谢综合征强相关。',
    reference: '男性性功能障碍诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/29311799/',
    riskFactors: ['肥胖/代谢综合征', '高血压糖尿病', '吸烟', '酗酒', '压力焦虑', '久坐缺乏运动'],
    genderNote: '男性专属：与心血管健康高度相关，ED 常是心血管疾病的早期信号。',
  },
  sperm_semen: {
    code: 'sperm_semen',
    scientificBasis: '精液质量评估依据 WHO 精液分析标准：精子浓度、活力、形态是核心；温度、氧化应激与内分泌影响生精。',
    reference: 'WHO 人类精液检查与处理实验室手册(第6版)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/33713040/',
    riskFactors: ['高温环境(久坐/泡澡)', '吸烟酗酒', '肥胖', '内分泌异常', '环境污染', '精索静脉曲张'],
    genderNote: '男性专属。',
  },
  immune_system: {
    code: 'immune_system',
    scientificBasis: '免疫功能评估基于免疫学：白细胞、淋巴细胞亚群、免疫球蛋白与 NK 细胞反映免疫状态；慢性压力、睡眠不足、营养不良抑制免疫。',
    reference: '免疫学基础；免疫衰老研究',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/30143636/',
    riskFactors: ['慢性压力', '睡眠不足', '营养缺乏', '久坐', '感染', '年龄增长(免疫衰老)'],
  },
  comprehensive_immunity: {
    code: 'comprehensive_immunity',
    scientificBasis: '综合免疫力评估整合免疫细胞、免疫球蛋白与炎症标志物，反映机体整体防御与炎症平衡。',
    reference: '免疫状态评估共识',
    riskFactors: ['长期压力', '睡眠紊乱', '营养不良', '慢性炎症', '缺乏运动'],
  },
  respiratory: {
    code: 'respiratory',
    scientificBasis: '呼吸功能评估依据肺功能学：肺活量、用力肺活量、气道阻力反映通气功能；吸烟与空气污染是主要损害因素。',
    reference: '中国慢性阻塞性肺疾病诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/30340968/',
    riskFactors: ['吸烟', '空气污染', '职业粉尘', '过敏', '反复感染'],
  },
  lung_function: {
    code: 'lung_function',
    scientificBasis: '肺功能评估基于肺通气与换气生理：肺活量、弥散功能、气道反应性决定呼吸效率。',
    reference: '肺功能检查指南(ATS/ERS)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/31558655/',
    riskFactors: ['吸烟', '哮喘/慢阻肺', '肥胖', '缺乏有氧运动', '粉尘暴露'],
  },
  brain_nerve: {
    code: 'brain_nerve',
    scientificBasis: '脑神经评估基于神经生理学：脑血流、神经递质、认知与情绪状态可通过自主神经指标(HRV、皮肤电)间接评估。',
    reference: '自主神经功能与脑健康(HRV 研究)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/26493429/',
    riskFactors: ['长期压力', '睡眠不足', '脑供血不足', '高血压', '久坐', '焦虑抑郁'],
  },
  cervical_vascular: {
    code: 'cervical_vascular',
    scientificBasis: '颈脑血管评估基于血流动力学：颈动脉血流、脑灌注与椎基底动脉供血反映脑循环；高血压与动脉硬化是主要病因。',
    reference: '脑血管病防治指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/29415230/',
    riskFactors: ['高血压', '高血脂', '吸烟', '糖尿病', '肥胖', '久坐低头(颈椎)'],
  },
  basic_constitution: {
    code: 'basic_constitution',
    scientificBasis: '基本体质评估结合中医体质学说(九种体质)与现代健康评估：平和/气虚/阳虚/阴虚/痰湿/湿热/血瘀/气郁/特禀体质有对应症状谱。',
    reference: '中医体质分类与判定(ZYYXH/T157-2009)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/23531565/',
    riskFactors: ['饮食偏嗜', '作息紊乱', '缺乏运动', '情志失调', '禀赋差异'],
  },
  comprehensive: {
    code: 'comprehensive',
    scientificBasis: '综合评估整合生命体征(心率/血压/血氧/体温)与代谢指标(BMI/基础代谢/疲劳/压力/睡眠)，给出整体健康画像。',
    reference: '健康管理综合评估框架',
    riskFactors: ['超重', '睡眠不足', '压力大', '久坐', '吸烟饮酒'],
  },
  body_fluid: {
    code: 'body_fluid',
    scientificBasis: '体液评估基于水盐代谢生理：细胞内/外液分布、电解质平衡由肾脏与内分泌共同调节，可通过 BIA 估算。',
    reference: '生物电阻抗体液分布测量',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/23299872/',
    riskFactors: ['饮水不足/过量', '电解质紊乱', '肾功能异常', '水肿', '利尿剂'],
  },
  body_toxin: {
    code: 'body_toxin',
    scientificBasis: '体内毒素/代谢废物评估基于肝肾解毒与代谢生理：肝脏解毒酶系与肾脏排泄决定代谢废物清除，可结合肝肾功能与氧化应激指标。',
    reference: '肝肾功能与氧化应激评估',
    riskFactors: ['饮酒', '熬夜', '药物', '高脂饮食', '环境污染', '便秘'],
  },
  heavy_metal: {
    code: 'heavy_metal',
    scientificBasis: '重金属暴露评估基于环境医学：铅、汞、镉、砷蓄积与职业暴露、饮食、环境污染相关，超标影响神经、肾与造血。',
    reference: 'WHO 重金属暴露健康风险评估',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/28838779/',
    riskFactors: ['职业暴露', '污染水源/食物', '劣质化妆品', '海鲜摄入', '吸烟'],
  },
  trace_elements: {
    code: 'trace_elements',
    scientificBasis: '微量元素评估基于营养学：钙铁锌硒碘镁铜等缺乏或过量影响酶活性、免疫、甲状腺与骨骼健康。',
    reference: '中国居民膳食营养素参考摄入量(DRIs)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/24347665/',
    riskFactors: ['饮食单一', '吸收不良', '特殊生理期(孕/哺乳)', '慢性病', '挑食'],
  },
  vitamins: {
    code: 'vitamins',
    scientificBasis: '维生素评估基于营养学：脂溶性(A/D/E/K)与水溶性(B族/C)维生素缺乏影响代谢、免疫、神经与骨骼。',
    reference: '维生素缺乏与健康(WHO/中国 DRIs)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/24347665/',
    riskFactors: ['蔬果摄入不足', '日照不足(维D)', '酗酒', '吸收不良', '特殊生理期'],
  },
  fatty_acid: {
    code: 'fatty_acid',
    scientificBasis: '脂肪酸评估基于脂类代谢：必需脂肪酸(ω-3/ω-6)平衡影响炎症、心血管与脑健康；反式脂肪有害。',
    reference: '脂肪酸与心血管健康(WHO 膳食脂肪指南)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/30244732/',
    riskFactors: ['高反式/饱和脂肪饮食', '深海鱼摄入不足', '肥胖', '代谢综合征'],
  },
  efa: {
    code: 'efa',
    scientificBasis: '基本脂肪酸(EFA)评估基于营养生化：亚油酸与 α-亚麻酸为人体必需脂肪酸，缺乏影响皮肤、免疫与神经发育。',
    reference: '必需脂肪酸营养学共识',
    riskFactors: ['低脂饮食过度', '植物油摄入单一', '吸收不良', '代谢异常'],
  },
  amino_acid: {
    code: 'amino_acid',
    scientificBasis: '氨基酸评估基于蛋白质代谢：必需氨基酸构成机体蛋白质，缺乏影响肌肉、免疫与合成代谢。',
    reference: '蛋白质与氨基酸营养(WHO/FAO)',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/17827208/',
    riskFactors: ['蛋白质摄入不足', '偏食', '吸收不良', '慢性消耗', '高强度运动'],
  },
  coenzyme: {
    code: 'coenzyme',
    scientificBasis: '辅酶评估基于能量代谢：辅酶 Q10 等参与线粒体呼吸链与抗氧化，随年龄下降，影响心脑能量供应。',
    reference: '辅酶 Q10 与线粒体功能研究',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/28931368/',
    riskFactors: ['年龄增长', '他汀类用药', '慢性疲劳', '心脑供血不足', '氧化应激'],
  },
  collagen: {
    code: 'collagen',
    scientificBasis: '胶原蛋白评估基于皮肤与结缔组织生理：胶原随年龄与氧化应激流失，影响皮肤弹性、关节与血管。',
    reference: '胶原蛋白代谢与衰老研究',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/27870207/',
    riskFactors: ['年龄增长', '紫外线', '吸烟', '高糖(糖化)', '维生素C缺乏'],
  },
  skin: {
    code: 'skin',
    scientificBasis: '皮肤评估基于皮肤生理：水分、油脂、弹性、色素与敏感度反映皮肤屏障与衰老状态。',
    reference: '皮肤屏障功能与衰老研究',
    riskFactors: ['紫外线', '熬夜', '高糖高油', '吸烟', '屏障受损', '激素波动'],
  },
  eye: {
    code: 'eye',
    scientificBasis: '眼健康评估基于视光学：屈光、眼压、视网膜微循环与视疲劳是核心，与用眼习惯和血管健康相关。',
    reference: '视疲劳与眼底血管健康共识',
    riskFactors: ['长时间近距离用眼', '蓝光暴露', '高血压糖尿病(眼底)', '睡眠不足', '年龄'],
  },
  meridian: {
    code: 'meridian',
    scientificBasis: '经络评估采用良导络(Ryodoraku)皮肤电测量法：中谷义雄(1950)发现经络反应点(良导点)皮肤电阻/电导与交感神经兴奋性相关，可用于自主神经与经络平衡评估。',
    reference: '中谷义雄良导络自律神经理论(日本良导络学会)',
    referenceUrl: 'https://www.jstage.jst.go.jp/browse/ryodoraku1968/30/11/_contents/-char/en',
    riskFactors: ['自主神经紊乱', '长期压力', '寒凉', '姿势劳损', '睡眠不足'],
  },
  gallbladder: {
    code: 'gallbladder',
    scientificBasis: '胆囊功能评估基于胆道生理：胆汁分泌、胆囊收缩与胆盐代谢影响脂肪消化；胆结石与高脂饮食、肥胖相关。',
    reference: '胆石症诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/27064687/',
    riskFactors: ['肥胖', '高脂高胆固醇饮食', '快速减重', '女性(雌激素)', '久坐', '不吃早餐'],
  },
  pancreas: {
    code: 'pancreas',
    scientificBasis: '胰腺功能评估基于内分泌(胰岛素/胰高血糖素)与外分泌(胰酶)双功能：糖代谢与消化吸收密切相关。',
    reference: '胰腺疾病诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/31905035/',
    riskFactors: ['高脂饮食', '酗酒', '胆道疾病', '高甘油三酯', '糖尿病'],
  },
  large_intestine: {
    code: 'large_intestine',
    scientificBasis: '大肠评估基于结直肠生理：蠕动、排便功能与肠道菌群影响消化排泄；膳食纤维与饮水是核心。',
    reference: '结直肠疾病筛查与便秘诊疗指南',
    referenceUrl: 'https://pubmed.ncbi.nlm.nih.gov/28690211/',
    riskFactors: ['低纤维饮食', '饮水不足', '久坐', '排便习惯不良', '肠道菌群紊乱', '年龄≥45'],
  },
  consciousness_posture: {
    code: 'consciousness_posture',
    scientificBasis: '体态评估基于运动医学：体态偏移(头前倾/圆肩/骨盆前倾)与肌肉失衡、姿势习惯相关，影响脊柱与关节负荷。',
    reference: '体态评估与运动康复共识',
    riskFactors: ['久坐', '低头族', '单侧负重', '核心肌群薄弱', '扁平足/步态异常'],
  },
  expert_analysis: {
    code: 'expert_analysis',
    scientificBasis: '专家分析为跨系统综合研判：汇总各器官系统评估结果，按风险分级排序，结合体质与生活方式给出优先级建议。',
    reference: '健康风险评估综合框架',
    riskFactors: ['多系统异常叠加', '未控制的基础病', '高危生活方式'],
  },
  manual_analysis: {
    code: 'manual_analysis',
    scientificBasis: '手工分析为医生/健康管理师人工判读留白：在系统评估基础上结合问诊、体检与实验室结果综合判断。',
    reference: '健康管理服务规范',
    riskFactors: [],
  },
};

export function getEvidence(code: string): EvidenceDef {
  return REPORT_EVIDENCE[code] || {
    code,
    scientificBasis: '基于人群流行病学与健康管理共识的健康风险评估。',
    reference: '健康管理通用评估框架',
    riskFactors: ['不良生活方式', '年龄/性别/遗传因素', '基础疾病'],
  };
}
